language: node_js
node_js: node
cache: 
directories:
- node_modules
deploy:
  provider: heroku
  api_key:
    secure: H1b08aRY7p02Gvc1xwYECL0TvTUD0+0ubA506cnYVHq2wC6C/ihnPYYUPOLTR9XTyZxTyAtpfE25tmPh75YSrk2OtUU1X0DH6SHYYryi8RdMLi1q+u0wJYEB/xqFqQZRab2wFBqSmPpo9fQGPpoVInaqk4F0CwC3RK7j9hpN7L/mhrbLkpok+uowhiKMvPfWsGZqSQT2xgMs/vKeiJ4MQwlyncSWwm3OabSpkjdX08iUbBz0cWxrrpJgGMmHqWR888XbdbL7uFFkqD0c4yx2XsucsxaHIBHSJJV8MYrXRrWM9c/MUQ5URKT5LHzmOzOg1gyx33HiEWZsiFKUDTl92Tm/DfwLxC8FsQa5muMeefnWTCLyiD11mwaCxL+3zOupD2lwiV4v+OXDjrDX0HwP4CN9HVz4RkpOA64mHunrzrbHsBoJTeXoUDpWGGBLxxsCMwiLYWHtIVKCwIzJvsxteiMFPF1EBeLP9NKlzQeM1ZnUMlLTHZcP6v5t7F5CHPp4sGs520RUWLsgp5EENvHaoP3t+aPMtyaQmOnOgQ7s47HhhsqTduX19sdK7FxhPeVx0wDPlqLJJ7qYo0OV2CgzYPs9i/yKYj3l2fenSXOMl1dDb03TaSuzCuK8+SQXbdVRrtmic+GiCw9qehROfyJLS2wxl3Z+MLlz1Fktkienjrs=
  app: priceguess
  on:
    repo: jnewby91/priceguess
